# Generated by Django 2.2 on 2020-08-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='new', max_length=30, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('task', 'Задача'), ('bug', 'Ошибка'), ('enhancement', 'Улучшение')], default='task', max_length=40, verbose_name='Тип задачи')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Полное описание')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='webapp.Status', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='webapp.Type', verbose_name='Type')),
            ],
        ),
    ]
